package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"sort"
	"strconv"
	"strings"

	"github.com/AkaraChen/ctxl/core/schema"
	"github.com/AkaraChen/ctxl/core/schema/loader"
	"github.com/AkaraChen/ctxl/core/skillbundle"
	"github.com/AkaraChen/ctxl/core/skillsgen"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/semver"
)

const (
	runtimeModule = "github.com/AkaraChen/ctxl"
	markerFile    = ".ctxl-generated"
	markerContent = "generated by ctxl; this directory is replaced in full\n"
)

type runtimeDependency struct {
	version string
	replace string
}

// Generate validates schemaPath and every referenced Skill, renders a complete
// generated command, and atomically replaces only a ctxl-owned output root.
func Generate(schemaPath string) (string, error) {
	return generate(schemaPath, runtimeDependency{version: linkedRuntimeVersion()})
}

func generate(schemaPath string, runtime runtimeDependency) (string, error) {
	absSchema, err := filepath.Abs(schemaPath)
	if err != nil {
		return "", err
	}
	s, err := loader.LoadFile(absSchema)
	if err != nil {
		return "", err
	}
	schemaDir := filepath.Dir(absSchema)
	bundle, err := skillsgen.Build(s, schemaDir)
	if err != nil {
		return "", err
	}
	version := s.Generation.CtxlVersion
	if version == "" {
		version = runtime.version
	}
	if version == "" && runtime.replace != "" {
		version = "v0.0.0"
	}
	if !semver.IsValid(version) {
		return "", fmt.Errorf("cannot determine a valid ctxl runtime version; set generation.ctxl_version in %s", absSchema)
	}

	target := filepath.Join(schemaDir, filepath.FromSlash(s.Generation.Output))
	target, err = filepath.Abs(target)
	if err != nil {
		return "", err
	}
	if err := validateTarget(target); err != nil {
		return "", err
	}
	if s.Generation.Mode == schema.GenerationExistingModule {
		if err := validateExistingModule(schemaDir, target, version); err != nil {
			return "", err
		}
	}
	mainSource, err := renderMain(s, bundle)
	if err != nil {
		return "", err
	}

	parent := filepath.Dir(target)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}
	tmp, err := os.MkdirTemp(parent, ".ctxl-render-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp)
	if err := writeGeneratedRoot(tmp, s, version, runtime.replace, mainSource); err != nil {
		return "", err
	}
	if s.Generation.Mode == schema.GenerationStandalone {
		if err := tidyStandalone(tmp); err != nil {
			return "", err
		}
	}
	if err := validateRenderedRoot(tmp, s.Generation.Mode); err != nil {
		return "", err
	}
	if err := replaceTarget(target, tmp); err != nil {
		return "", err
	}
	return target, nil
}

func tidyStandalone(root string) error {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("prepare standalone module: go mod tidy: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func linkedRuntimeVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
	if info.Main.Path == runtimeModule && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	for _, dep := range info.Deps {
		if dep.Path == runtimeModule && dep.Version != "" && dep.Version != "(devel)" {
			return dep.Version
		}
	}
	return ""
}

func validateExistingModule(schemaDir, target, version string) error {
	goModPath, err := findGoMod(schemaDir)
	if err != nil {
		return err
	}
	moduleRoot := filepath.Dir(goModPath)
	rel, err := filepath.Rel(moduleRoot, target)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("existing-module output %s must be inside module %s", target, moduleRoot)
	}
	raw, err := os.ReadFile(goModPath)
	if err != nil {
		return err
	}
	parsed, err := modfile.Parse(goModPath, raw, nil)
	if err != nil {
		return fmt.Errorf("parse %s: %w", goModPath, err)
	}
	if parsed.Module != nil && parsed.Module.Mod.Path == runtimeModule {
		return nil
	}
	for _, require := range parsed.Require {
		if require.Mod.Path == runtimeModule && require.Mod.Version == version {
			return nil
		}
	}
	return fmt.Errorf("%s must require ctxl %s; run: go get %s@%s", goModPath, version, runtimeModule, version)
}

func findGoMod(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		path := filepath.Join(dir, "go.mod")
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			return path, nil
		} else if err != nil && !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("existing-module mode requires a parent go.mod")
		}
		dir = parent
	}
}

func renderMain(s schema.Schema, bundle skillbundle.Bundle) ([]byte, error) {
	skillValues := make([]ast.Expr, 0, len(bundle.Skills))
	for _, skill := range bundle.Skills {
		entryValues := make([]ast.Expr, 0, len(skill.Entries))
		for _, entry := range skill.Entries {
			entryValues = append(entryValues, &ast.CompositeLit{
				Type: selector("skillbundle", "Entry"),
				Elts: []ast.Expr{
					keyValue("Path", stringLiteral(entry.Path)),
					keyValue("Mode", &ast.BasicLit{Kind: token.INT, Value: strconv.FormatUint(uint64(entry.Mode), 10)}),
					keyValue("Directory", ast.NewIdent(strconv.FormatBool(entry.Directory))),
					keyValue("Data", byteSlice(entry.Data)),
				},
			})
		}
		skillValues = append(skillValues, &ast.CompositeLit{
			Type: selector("skillbundle", "Skill"),
			Elts: []ast.Expr{
				keyValue("Name", stringLiteral(skill.Name)),
				keyValue("Entries", &ast.CompositeLit{Type: &ast.ArrayType{Elt: selector("skillbundle", "Entry")}, Elts: entryValues}),
			},
		})
	}

	file := &ast.File{
		Doc:  &ast.CommentGroup{List: []*ast.Comment{{Text: "// Code generated by ctxl. DO NOT EDIT."}}},
		Name: ast.NewIdent("main"),
		Decls: []ast.Decl{
			&ast.GenDecl{Tok: token.IMPORT, Specs: []ast.Spec{
				importSpec("fmt"),
				importSpec("os"),
				importSpec("github.com/AkaraChen/ctxl/cli"),
				importSpec("github.com/AkaraChen/ctxl/core/schema"),
				importSpec("github.com/AkaraChen/ctxl/core/skillbundle"),
			}},
			varDecl("activeSchema", schemaLiteral(s)),
			varDecl("bundledSkills", &ast.CompositeLit{
				Type: selector("skillbundle", "Bundle"),
				Elts: []ast.Expr{keyValue("Skills", &ast.CompositeLit{
					Type: &ast.ArrayType{Elt: selector("skillbundle", "Skill")},
					Elts: skillValues,
				})},
			}),
			mainDecl(),
		},
	}
	var b bytes.Buffer
	err := format.Node(&b, token.NewFileSet(), file)
	if err != nil {
		return nil, fmt.Errorf("format generated main.go: %w", err)
	}
	return b.Bytes(), nil
}

func mainDecl() *ast.FuncDecl {
	options := &ast.CompositeLit{
		Type: selector("cli", "Options"),
		Elts: []ast.Expr{
			keyValue("Schema", ast.NewIdent("activeSchema")),
			keyValue("Skills", ast.NewIdent("bundledSkills")),
		},
	}
	newCLI := &ast.CallExpr{Fun: selector("cli", "New"), Args: []ast.Expr{options}}
	execute := &ast.CallExpr{Fun: &ast.SelectorExpr{X: newCLI, Sel: ast.NewIdent("Execute")}}
	executeFailure := &ast.IfStmt{
		Init: &ast.AssignStmt{Lhs: []ast.Expr{ast.NewIdent("err")}, Tok: token.DEFINE, Rhs: []ast.Expr{execute}},
		Cond: notNil("err"),
		Body: &ast.BlockStmt{List: []ast.Stmt{
			exprStmt(call("fmt", "Fprintf", selector("os", "Stderr"), stringLiteral("%s: %v\n"), selectorExpr(selectorExpr(ast.NewIdent("activeSchema"), "CLI"), "Name"), ast.NewIdent("err"))),
			exprStmt(call("os", "Exit", intLiteral(1))),
		}},
	}
	return &ast.FuncDecl{
		Name: ast.NewIdent("main"),
		Type: &ast.FuncType{Params: &ast.FieldList{}},
		Body: &ast.BlockStmt{List: []ast.Stmt{executeFailure}},
	}
}

func schemaLiteral(s schema.Schema) ast.Expr {
	skills := make([]ast.Expr, 0, len(s.Skills))
	for _, skill := range s.Skills {
		skills = append(skills, &ast.CompositeLit{
			Type: selector("schema", "Skill"),
			Elts: []ast.Expr{
				keyValue("Type", stringLiteral(string(skill.Type))),
				keyValue("Directory", stringLiteral(skill.Directory)),
				keyValue("Inject", stringLiteral(string(skill.Inject))),
				keyValue("Name", stringLiteral(skill.Name)),
				keyValue("Description", stringLiteral(skill.Description)),
				keyValue("License", stringLiteral(skill.License)),
				keyValue("Compatibility", stringLiteral(skill.Compatibility)),
				keyValue("Metadata", stringMapLiteral(skill.Metadata)),
				keyValue("AllowedTools", stringLiteral(skill.AllowedTools)),
			},
		})
	}
	entities := make([]ast.Expr, 0, len(s.Entities))
	for _, entity := range s.Entities {
		fields := make([]ast.Expr, 0, len(entity.Fields))
		for _, field := range entity.Fields {
			fields = append(fields, &ast.CompositeLit{
				Type: selector("schema", "Field"),
				Elts: []ast.Expr{
					keyValue("Name", stringLiteral(field.Name)),
					keyValue("Type", stringLiteral(string(field.Type))),
					keyValue("Required", ast.NewIdent(strconv.FormatBool(field.Required))),
					keyValue("Description", stringLiteral(field.Description)),
				},
			})
		}
		entities = append(entities, &ast.CompositeLit{
			Type: selector("schema", "Entity"),
			Elts: []ast.Expr{
				keyValue("Name", stringLiteral(entity.Name)),
				keyValue("Kind", stringLiteral(string(entity.Kind))),
				keyValue("Format", stringLiteral(string(entity.Format))),
				keyValue("Path", stringLiteral(entity.Path)),
				keyValue("Location", stringLiteral(string(entity.Location))),
				keyValue("Scope", stringLiteral(string(entity.Scope))),
				keyValue("ID", stringLiteral(entity.ID)),
				keyValue("Write", stringLiteral(string(entity.Write))),
				keyValue("Section", stringLiteral(entity.Section)),
				keyValue("Target", stringLiteral(entity.Target)),
				keyValue("Body", stringLiteral(entity.Body)),
				keyValue("Description", stringLiteral(entity.Description)),
				keyValue("Command", &ast.CompositeLit{Type: selector("schema", "NameOverride"), Elts: []ast.Expr{keyValue("Name", stringLiteral(entity.Command.Name))}}),
				keyValue("Fields", &ast.CompositeLit{Type: &ast.ArrayType{Elt: selector("schema", "Field")}, Elts: fields}),
			},
		})
	}
	return &ast.CompositeLit{
		Type: selector("schema", "Schema"),
		Elts: []ast.Expr{
			keyValue("SchemaURL", stringLiteral(s.SchemaURL)),
			keyValue("Name", stringLiteral(s.Name)),
			keyValue("Description", stringLiteral(s.Description)),
			keyValue("Generation", &ast.CompositeLit{Type: selector("schema", "Generation"), Elts: []ast.Expr{
				keyValue("Mode", stringLiteral(string(s.Generation.Mode))),
				keyValue("Output", stringLiteral(s.Generation.Output)),
				keyValue("Module", stringLiteral(s.Generation.Module)),
				keyValue("CtxlVersion", stringLiteral(s.Generation.CtxlVersion)),
			}}),
			keyValue("CLI", &ast.CompositeLit{Type: selector("schema", "NameOverride"), Elts: []ast.Expr{keyValue("Name", stringLiteral(s.CLI.Name))}}),
			keyValue("Store", &ast.CompositeLit{Type: selector("schema", "NameOverride"), Elts: []ast.Expr{keyValue("Name", stringLiteral(s.Store.Name))}}),
			keyValue("Skills", &ast.CompositeLit{Type: &ast.ArrayType{Elt: selector("schema", "Skill")}, Elts: skills}),
			keyValue("Entities", &ast.CompositeLit{Type: &ast.ArrayType{Elt: selector("schema", "Entity")}, Elts: entities}),
		},
	}
}

func stringMapLiteral(values map[string]string) ast.Expr {
	if values == nil {
		return ast.NewIdent("nil")
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	elements := make([]ast.Expr, 0, len(keys))
	for _, key := range keys {
		elements = append(elements, &ast.KeyValueExpr{Key: stringLiteral(key), Value: stringLiteral(values[key])})
	}
	return &ast.CompositeLit{Type: &ast.MapType{Key: ast.NewIdent("string"), Value: ast.NewIdent("string")}, Elts: elements}
}

func importSpec(path string) *ast.ImportSpec {
	return &ast.ImportSpec{Path: stringLiteral(path)}
}

func varDecl(name string, value ast.Expr) *ast.GenDecl {
	return &ast.GenDecl{Tok: token.VAR, Specs: []ast.Spec{&ast.ValueSpec{Names: []*ast.Ident{ast.NewIdent(name)}, Values: []ast.Expr{value}}}}
}

func keyValue(key string, value ast.Expr) *ast.KeyValueExpr {
	return &ast.KeyValueExpr{Key: ast.NewIdent(key), Value: value}
}

func stringLiteral(value string) *ast.BasicLit {
	return &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(value)}
}

func intLiteral(value int) *ast.BasicLit {
	return &ast.BasicLit{Kind: token.INT, Value: strconv.Itoa(value)}
}

func byteSlice(value []byte) *ast.CallExpr {
	return &ast.CallExpr{Fun: &ast.ArrayType{Elt: ast.NewIdent("byte")}, Args: []ast.Expr{stringLiteral(string(value))}}
}

func selector(pkg, name string) *ast.SelectorExpr {
	return selectorExpr(ast.NewIdent(pkg), name)
}

func selectorExpr(expr ast.Expr, name string) *ast.SelectorExpr {
	return &ast.SelectorExpr{X: expr, Sel: ast.NewIdent(name)}
}

func call(pkg, name string, args ...ast.Expr) *ast.CallExpr {
	return &ast.CallExpr{Fun: selector(pkg, name), Args: args}
}

func exprStmt(expr ast.Expr) *ast.ExprStmt {
	return &ast.ExprStmt{X: expr}
}

func notNil(name string) *ast.BinaryExpr {
	return &ast.BinaryExpr{X: ast.NewIdent(name), Op: token.NEQ, Y: ast.NewIdent("nil")}
}

func writeGeneratedRoot(root string, s schema.Schema, version, replace string, mainSource []byte) error {
	if err := os.WriteFile(filepath.Join(root, markerFile), []byte(markerContent), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, "main.go"), mainSource, 0o644); err != nil {
		return err
	}
	if s.Generation.Mode != schema.GenerationStandalone {
		return nil
	}
	mod := new(modfile.File)
	if err := mod.AddModuleStmt(s.Generation.Module); err != nil {
		return err
	}
	if err := mod.AddGoStmt("1.24.0"); err != nil {
		return err
	}
	if err := mod.AddRequire(runtimeModule, version); err != nil {
		return err
	}
	if replace != "" {
		absReplace, err := filepath.Abs(replace)
		if err != nil {
			return err
		}
		if err := mod.AddReplace(runtimeModule, "", absReplace, ""); err != nil {
			return err
		}
	}
	mod.Cleanup()
	formatted, err := mod.Format()
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, "go.mod"), formatted, 0o644)
}

func validateRenderedRoot(root string, mode schema.GenerationMode) error {
	raw, err := os.ReadFile(filepath.Join(root, "main.go"))
	if err != nil {
		return err
	}
	if _, err := format.Source(raw); err != nil {
		return fmt.Errorf("generated main.go is invalid: %w", err)
	}
	if mode == schema.GenerationStandalone {
		raw, err := os.ReadFile(filepath.Join(root, "go.mod"))
		if err != nil {
			return err
		}
		if _, err := modfile.Parse("go.mod", raw, nil); err != nil {
			return fmt.Errorf("generated go.mod is invalid: %w", err)
		}
	}
	return nil
}

func validateTarget(target string) error {
	info, err := os.Lstat(target)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("generated output %s exists and is not a directory", target)
	}
	marker, err := os.ReadFile(filepath.Join(target, markerFile))
	if err == nil && string(marker) == markerContent {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	entries, err := os.ReadDir(target)
	if err != nil {
		return err
	}
	if len(entries) != 0 {
		return fmt.Errorf("refusing to replace unmarked non-empty directory %s", target)
	}
	return nil
}

func replaceTarget(target, rendered string) error {
	_, err := os.Lstat(target)
	if os.IsNotExist(err) {
		return os.Rename(rendered, target)
	}
	if err != nil {
		return err
	}
	parent := filepath.Dir(target)
	backup, err := os.MkdirTemp(parent, ".ctxl-backup-")
	if err != nil {
		return err
	}
	if err := os.Remove(backup); err != nil {
		return err
	}
	if err := os.Rename(target, backup); err != nil {
		return err
	}
	if err := os.Rename(rendered, target); err != nil {
		_ = os.Rename(backup, target)
		return err
	}
	if err := os.RemoveAll(backup); err != nil {
		return fmt.Errorf("generated output replaced but old backup %s could not be removed: %w", backup, err)
	}
	return nil
}
