package codegen

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"runtime/debug"
	"strings"

	"github.com/AkaraChen/ctxl/core/schema"
	"github.com/AkaraChen/ctxl/core/schema/loader"
	"github.com/AkaraChen/ctxl/core/skillbundle"
	"github.com/AkaraChen/ctxl/core/skillsgen"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/semver"
)

const (
	runtimeModule = "github.com/AkaraChen/ctxl"
	markerFile    = ".ctxl-generated"
	markerContent = "generated by ctxl; this directory is replaced in full\n"
)

type runtimeDependency struct {
	version string
	replace string
}

// Generate validates schemaPath and every referenced Skill, renders a complete
// generated command, and atomically replaces only a ctxl-owned output root.
func Generate(schemaPath string) (string, error) {
	return generate(schemaPath, runtimeDependency{version: linkedRuntimeVersion()})
}

func generate(schemaPath string, runtime runtimeDependency) (string, error) {
	absSchema, err := filepath.Abs(schemaPath)
	if err != nil {
		return "", err
	}
	s, err := loader.LoadFile(absSchema)
	if err != nil {
		return "", err
	}
	schemaDir := filepath.Dir(absSchema)
	bundle, err := skillsgen.Build(s, schemaDir)
	if err != nil {
		return "", err
	}
	version := s.Generation.CtxlVersion
	if version == "" {
		version = runtime.version
	}
	if version == "" && runtime.replace != "" {
		version = "v0.0.0"
	}
	if !semver.IsValid(version) {
		return "", fmt.Errorf("cannot determine a valid ctxl runtime version; set generation.ctxl_version in %s", absSchema)
	}

	target := filepath.Join(schemaDir, filepath.FromSlash(s.Generation.Output))
	target, err = filepath.Abs(target)
	if err != nil {
		return "", err
	}
	if err := validateTarget(target); err != nil {
		return "", err
	}
	if s.Generation.Mode == schema.GenerationExistingModule {
		if err := validateExistingModule(schemaDir, target, version); err != nil {
			return "", err
		}
	}
	mainSource, err := renderMain(s, bundle)
	if err != nil {
		return "", err
	}

	parent := filepath.Dir(target)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}
	tmp, err := os.MkdirTemp(parent, ".ctxl-render-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp)
	if err := writeGeneratedRoot(tmp, s, version, runtime.replace, mainSource); err != nil {
		return "", err
	}
	if s.Generation.Mode == schema.GenerationStandalone {
		if err := tidyStandalone(tmp); err != nil {
			return "", err
		}
	}
	if err := replaceTarget(target, tmp); err != nil {
		return "", err
	}
	return target, nil
}

func tidyStandalone(root string) error {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("prepare standalone module: go mod tidy: %w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func linkedRuntimeVersion() string {
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return ""
	}
	if info.Main.Path == runtimeModule && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	for _, dep := range info.Deps {
		if dep.Path == runtimeModule && dep.Version != "" && dep.Version != "(devel)" {
			return dep.Version
		}
	}
	return ""
}

func validateExistingModule(schemaDir, target, version string) error {
	goModPath, err := findGoMod(schemaDir)
	if err != nil {
		return err
	}
	moduleRoot := filepath.Dir(goModPath)
	rel, err := filepath.Rel(moduleRoot, target)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("existing-module output %s must be inside module %s", target, moduleRoot)
	}
	raw, err := os.ReadFile(goModPath)
	if err != nil {
		return err
	}
	parsed, err := modfile.Parse(goModPath, raw, nil)
	if err != nil {
		return fmt.Errorf("parse %s: %w", goModPath, err)
	}
	if parsed.Module != nil && parsed.Module.Mod.Path == runtimeModule {
		return nil
	}
	for _, require := range parsed.Require {
		if require.Mod.Path == runtimeModule && require.Mod.Version == version {
			return nil
		}
	}
	return fmt.Errorf("%s must require ctxl %s; run: go get %s@%s", goModPath, version, runtimeModule, version)
}

func findGoMod(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		path := filepath.Join(dir, "go.mod")
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			return path, nil
		} else if err != nil && !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("existing-module mode requires a parent go.mod")
		}
		dir = parent
	}
}

// renderMain prints the normalized schema and Skill bundle as Go composite
// literals (%#v is deterministic: fmt sorts map keys) inside a fixed entrypoint.
func renderMain(s schema.Schema, bundle skillbundle.Bundle) ([]byte, error) {
	src := fmt.Sprintf(`// Code generated by ctxl. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	"github.com/AkaraChen/ctxl/cli"
	"github.com/AkaraChen/ctxl/core/schema"
	"github.com/AkaraChen/ctxl/core/skillbundle"
)

var activeSchema = %#v

var bundledSkills = %#v

func main() {
	if err := cli.New(cli.Options{Schema: activeSchema, Skills: bundledSkills}).Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "%%s: %%v\n", activeSchema.CLI.Name, err)
		os.Exit(1)
	}
}
`, s, bundle)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("format generated main.go: %w", err)
	}
	return formatted, nil
}

func writeGeneratedRoot(root string, s schema.Schema, version, replace string, mainSource []byte) error {
	if err := os.WriteFile(filepath.Join(root, markerFile), []byte(markerContent), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, "main.go"), mainSource, 0o644); err != nil {
		return err
	}
	if s.Generation.Mode != schema.GenerationStandalone {
		return nil
	}
	mod := new(modfile.File)
	if err := mod.AddModuleStmt(s.Generation.Module); err != nil {
		return err
	}
	if err := mod.AddGoStmt("1.24.0"); err != nil {
		return err
	}
	if err := mod.AddRequire(runtimeModule, version); err != nil {
		return err
	}
	if replace != "" {
		absReplace, err := filepath.Abs(replace)
		if err != nil {
			return err
		}
		if err := mod.AddReplace(runtimeModule, "", absReplace, ""); err != nil {
			return err
		}
	}
	mod.Cleanup()
	formatted, err := mod.Format()
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(root, "go.mod"), formatted, 0o644)
}

func validateTarget(target string) error {
	info, err := os.Lstat(target)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("generated output %s exists and is not a directory", target)
	}
	marker, err := os.ReadFile(filepath.Join(target, markerFile))
	if err == nil && string(marker) == markerContent {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	entries, err := os.ReadDir(target)
	if err != nil {
		return err
	}
	if len(entries) != 0 {
		return fmt.Errorf("refusing to replace unmarked non-empty directory %s", target)
	}
	return nil
}

func replaceTarget(target, rendered string) error {
	_, err := os.Lstat(target)
	if os.IsNotExist(err) {
		return os.Rename(rendered, target)
	}
	if err != nil {
		return err
	}
	parent := filepath.Dir(target)
	backup, err := os.MkdirTemp(parent, ".ctxl-backup-")
	if err != nil {
		return err
	}
	if err := os.Remove(backup); err != nil {
		return err
	}
	if err := os.Rename(target, backup); err != nil {
		return err
	}
	if err := os.Rename(rendered, target); err != nil {
		_ = os.Rename(backup, target)
		return err
	}
	if err := os.RemoveAll(backup); err != nil {
		return fmt.Errorf("generated output replaced but old backup %s could not be removed: %w", backup, err)
	}
	return nil
}
