// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schemajson

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "unicode/utf8"

type BuiltinSkill struct {
	// AllowedTools corresponds to the JSON schema field "allowed-tools".
	AllowedTools *string `json:"allowed-tools,omitempty,omitzero"`

	// Compatibility corresponds to the JSON schema field "compatibility".
	Compatibility *string `json:"compatibility,omitempty,omitzero"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero"`

	// Directory corresponds to the JSON schema field "directory".
	Directory *RelativePath `json:"directory,omitempty,omitzero"`

	// Inject corresponds to the JSON schema field "inject".
	Inject BuiltinSkillInject `json:"inject,omitempty,omitzero"`

	// License corresponds to the JSON schema field "license".
	License *string `json:"license,omitempty,omitzero"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata BuiltinSkillMetadata `json:"metadata,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name *SkillName `json:"name,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

type BuiltinSkillInject string

const BuiltinSkillInjectAfter BuiltinSkillInject = "after"
const BuiltinSkillInjectBefore BuiltinSkillInject = "before"

var enumValues_BuiltinSkillInject = []interface{}{
	"before",
	"after",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BuiltinSkillInject) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BuiltinSkillInject {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BuiltinSkillInject, v)
	}
	*j = BuiltinSkillInject(v)
	return nil
}

type BuiltinSkillMetadata map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *BuiltinSkill) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in BuiltinSkill: required")
	}
	type Plain BuiltinSkill
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AllowedTools != nil && utf8.RuneCountInString(string(*plain.AllowedTools)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "allowed-tools", 1)
	}
	if plain.Compatibility != nil && utf8.RuneCountInString(string(*plain.Compatibility)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "compatibility", 1)
	}
	if plain.Compatibility != nil && utf8.RuneCountInString(string(*plain.Compatibility)) > 500 {
		return fmt.Errorf("field %s length: must be <= %d", "compatibility", 500)
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "description", 1)
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) > 1024 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 1024)
	}
	if v, ok := raw["inject"]; !ok || v == nil {
		plain.Inject = "after"
	}
	if plain.License != nil && utf8.RuneCountInString(string(*plain.License)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "license", 1)
	}
	*j = BuiltinSkill(plain)
	return nil
}

type CommandName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *CommandName) UnmarshalJSON(value []byte) error {
	type Plain CommandName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Za-z0-9][A-Za-z0-9._-]*$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	*j = CommandName(plain)
	return nil
}

type CustomSkill struct {
	// Directory corresponds to the JSON schema field "directory".
	Directory RelativePath `json:"directory"`

	// Type corresponds to the JSON schema field "type".
	Type interface{} `json:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CustomSkill) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["directory"]; raw != nil && !ok {
		return fmt.Errorf("field directory in CustomSkill: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in CustomSkill: required")
	}
	type Plain CustomSkill
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CustomSkill(plain)
	return nil
}

type Document struct {
	// Schema corresponds to the JSON schema field "$schema".
	Schema *string `json:"$schema,omitempty,omitzero"`

	// Cli corresponds to the JSON schema field "cli".
	Cli *NameOverride `json:"cli,omitempty,omitzero"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero"`

	// Entities corresponds to the JSON schema field "entities".
	Entities []Entity `json:"entities"`

	// Generation corresponds to the JSON schema field "generation".
	Generation Generation `json:"generation,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name CommandName `json:"name"`

	// Skills corresponds to the JSON schema field "skills".
	Skills Skills `json:"skills,omitempty,omitzero"`

	// Store corresponds to the JSON schema field "store".
	Store *NameOverride `json:"store,omitempty,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Document) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["entities"]; raw != nil && !ok {
		return fmt.Errorf("field entities in Document: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Document: required")
	}
	type Plain Document
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && utf8.RuneCountInString(string(*plain.Description)) > 1024 {
		return fmt.Errorf("field %s length: must be <= %d", "description", 1024)
	}
	if plain.Entities != nil && len(plain.Entities) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "entities", 1)
	}
	if v, ok := raw["generation"]; !ok || v == nil {
		plain.Generation = Generation{
			Mode: "standalone",
		}
	}
	if v, ok := raw["skills"]; !ok || v == nil {
		plain.Skills = Skills{}
	}
	*j = Document(plain)
	return nil
}

type Entity struct {
	// Body corresponds to the JSON schema field "body".
	Body *string `json:"body,omitempty,omitzero"`

	// Command corresponds to the JSON schema field "command".
	Command *EntityCommand `json:"command,omitempty,omitzero"`

	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero"`

	// Fields corresponds to the JSON schema field "fields".
	Fields []Field `json:"fields,omitempty,omitzero"`

	// Format corresponds to the JSON schema field "format".
	Format EntityFormat `json:"format"`

	// Id corresponds to the JSON schema field "id".
	Id CommandName `json:"id,omitempty,omitzero"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EntityKind `json:"kind"`

	// Location corresponds to the JSON schema field "location".
	Location EntityLocation `json:"location,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name EntityCommandName `json:"name"`

	// Path corresponds to the JSON schema field "path".
	Path RelativePath `json:"path"`

	// Scope corresponds to the JSON schema field "scope".
	Scope EntityScope `json:"scope,omitempty,omitzero"`

	// Section corresponds to the JSON schema field "section".
	Section *string `json:"section,omitempty,omitzero"`

	// Target corresponds to the JSON schema field "target".
	Target *string `json:"target,omitempty,omitzero"`

	// Write corresponds to the JSON schema field "write".
	Write EntityWrite `json:"write,omitempty,omitzero"`
}

type EntityCommand struct {
	// Name corresponds to the JSON schema field "name".
	Name *EntityCommandName `json:"name,omitempty,omitzero"`
}

type EntityCommandName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityCommandName) UnmarshalJSON(value []byte) error {
	type Plain EntityCommandName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Za-z0-9][A-Za-z0-9._-]*$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	*j = EntityCommandName(plain)
	return nil
}

type EntityFormat string

const EntityFormatMarkdown EntityFormat = "markdown"
const EntityFormatNdjson EntityFormat = "ndjson"
const EntityFormatSymlink EntityFormat = "symlink"

var enumValues_EntityFormat = []interface{}{
	"markdown",
	"ndjson",
	"symlink",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityFormat) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EntityFormat {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EntityFormat, v)
	}
	*j = EntityFormat(v)
	return nil
}

type EntityKind string

const EntityKindPlural EntityKind = "plural"
const EntityKindSingular EntityKind = "singular"

var enumValues_EntityKind = []interface{}{
	"singular",
	"plural",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EntityKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EntityKind, v)
	}
	*j = EntityKind(v)
	return nil
}

type EntityLocation string

const EntityLocationRoot EntityLocation = "root"
const EntityLocationStore EntityLocation = "store"

var enumValues_EntityLocation = []interface{}{
	"root",
	"store",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityLocation) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EntityLocation {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EntityLocation, v)
	}
	*j = EntityLocation(v)
	return nil
}

type EntityScope string

const EntityScopeBoth EntityScope = "both"
const EntityScopeGlobal EntityScope = "global"
const EntityScopeProject EntityScope = "project"

var enumValues_EntityScope = []interface{}{
	"project",
	"global",
	"both",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityScope) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EntityScope {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EntityScope, v)
	}
	*j = EntityScope(v)
	return nil
}

type EntityWrite string

const EntityWriteReplace EntityWrite = "replace"
const EntityWriteSection EntityWrite = "section"

var enumValues_EntityWrite = []interface{}{
	"replace",
	"section",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EntityWrite) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EntityWrite {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EntityWrite, v)
	}
	*j = EntityWrite(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Entity) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["format"]; raw != nil && !ok {
		return fmt.Errorf("field format in Entity: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Entity: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Entity: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in Entity: required")
	}
	type Plain Entity
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["fields"]; !ok || v == nil {
		plain.Fields = []Field{}
	}
	if v, ok := raw["id"]; !ok || v == nil {
		plain.Id = "id"
	}
	if v, ok := raw["location"]; !ok || v == nil {
		plain.Location = "store"
	}
	if v, ok := raw["scope"]; !ok || v == nil {
		plain.Scope = "both"
	}
	if plain.Section != nil && utf8.RuneCountInString(string(*plain.Section)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "section", 1)
	}
	if plain.Target != nil && utf8.RuneCountInString(string(*plain.Target)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "target", 1)
	}
	if v, ok := raw["write"]; !ok || v == nil {
		plain.Write = "replace"
	}
	*j = Entity(plain)
	return nil
}

type Field struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty,omitzero"`

	// Name corresponds to the JSON schema field "name".
	Name FieldName `json:"name"`

	// Required corresponds to the JSON schema field "required".
	Required *bool `json:"required,omitempty,omitzero"`

	// Type corresponds to the JSON schema field "type".
	Type FieldType `json:"type"`
}

type FieldName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *FieldName) UnmarshalJSON(value []byte) error {
	type Plain FieldName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Za-z0-9][A-Za-z0-9._-]*$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	*j = FieldName(plain)
	return nil
}

type FieldType string

const FieldTypeInt FieldType = "int"
const FieldTypeObject FieldType = "object"
const FieldTypeString FieldType = "string"

var enumValues_FieldType = []interface{}{
	"string",
	"int",
	"object",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FieldType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_FieldType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_FieldType, v)
	}
	*j = FieldType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Field) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Field: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Field: required")
	}
	type Plain Field
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Field(plain)
	return nil
}

type Generation struct {
	// CtxlVersion corresponds to the JSON schema field "ctxl_version".
	CtxlVersion *string `json:"ctxl_version,omitempty,omitzero"`

	// Mode corresponds to the JSON schema field "mode".
	Mode GenerationMode `json:"mode,omitempty,omitzero"`

	// Module corresponds to the JSON schema field "module".
	Module *string `json:"module,omitempty,omitzero"`

	// Output corresponds to the JSON schema field "output".
	Output *RelativePath `json:"output,omitempty,omitzero"`
}

type GenerationMode string

const GenerationModeExistingModule GenerationMode = "existing-module"
const GenerationModeStandalone GenerationMode = "standalone"

var enumValues_GenerationMode = []interface{}{
	"standalone",
	"existing-module",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *GenerationMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_GenerationMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_GenerationMode, v)
	}
	*j = GenerationMode(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Generation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain Generation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CtxlVersion != nil {
		if matched, _ := regexp.MatchString(`^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$`, string(*plain.CtxlVersion)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "CtxlVersion", `^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$`)
		}
	}
	if v, ok := raw["mode"]; !ok || v == nil {
		plain.Mode = "standalone"
	}
	if plain.Module != nil && utf8.RuneCountInString(string(*plain.Module)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "module", 1)
	}
	*j = Generation(plain)
	return nil
}

type NameOverride struct {
	// Name corresponds to the JSON schema field "name".
	Name *CommandName `json:"name,omitempty,omitzero"`
}

type RelativePath string

// UnmarshalJSON implements json.Unmarshaler.
func (j *RelativePath) UnmarshalJSON(value []byte) error {
	type Plain RelativePath
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[^/\\]`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[^/\\]`)
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	*j = RelativePath(plain)
	return nil
}

type SkillName string

// UnmarshalJSON implements json.Unmarshaler.
func (j *SkillName) UnmarshalJSON(value []byte) error {
	type Plain SkillName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z0-9]+(?:-[a-z0-9]+)*$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z0-9]+(?:-[a-z0-9]+)*$`)
	}
	if utf8.RuneCountInString(string(plain)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "", 1)
	}
	if utf8.RuneCountInString(string(plain)) > 64 {
		return fmt.Errorf("field %s length: must be <= %d", "", 64)
	}
	*j = SkillName(plain)
	return nil
}

type Skills []interface{}
